models:
  prophet:
    changepoint_prior_scale: 0.05
    holidays_prior_scale: 0.15
    seasonality:
      monthly:
        period: 30.5
        fourier_order: 5
      payday:
        period: 14
        fourier_order: 3

  arima:
    default_order: [1, 1, 1]
    seasonal_order: [1, 1, 1, 7]

zim_specific:
  critical_skus: ["MEALIE_2KG", "COOKOIL_2LT", "BREAD_LOAF"]
  payday_weeks: [1, 3]  # 1st and 3rd weeks of month